// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android: return android;
      case TargetPlatform.iOS: return ios;
      case TargetPlatform.macOS: return macos;
      case TargetPlatform.windows: return windows;
      case TargetPlatform.linux: throw UnsupportedError('DefaultFirebaseOptions have not been configured for linux.');
      default: throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2YNDAPbY0sjoD4hQNYFPzegMUc1jTRPU',
    appId: '1:409947639600:web:7ac78607878cebf4f2c2f5',
    messagingSenderId: '409947639600',
    projectId: 'stellar-pos-8384a',
    authDomain: 'stellar-pos-8384a.firebaseapp.com',
    storageBucket: 'stellar-pos-8384a.firebasestorage.app',
    measurementId: 'G-L51DN9J9L7',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg-EHn5WPOiyMgdAiih3wewSaMyVUW34M',
    appId: '1:409947639600:android:3c1f0e4dba14461bf2c2f5',
    messagingSenderId: '409947639600',
    projectId: 'stellar-pos-8384a',
    storageBucket: 'stellar-pos-8384a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOYr_FE9lsgw3vA0G7zk34a9gkpqTJjL0',
    appId: '1:409947639600:ios:e4831912aa244bb7f2c2f5',
    messagingSenderId: '409947639600',
    projectId: 'stellar-pos-8384a',
    storageBucket: 'stellar-pos-8384a.firebasestorage.app',
    iosBundleId: 'com.example.stellarPos',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOYr_FE9lsgw3vA0G7zk34a9gkpqTJjL0',
    appId: '1:409947639600:ios:e4831912aa244bb7f2c2f5',
    messagingSenderId: '409947639600',
    projectId: 'stellar-pos-8384a',
    storageBucket: 'stellar-pos-8384a.firebasestorage.app',
    iosBundleId: 'com.example.stellarPos',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2YNDAPbY0sjoD4hQNYFPzegMUc1jTRPU',
    appId: '1:409947639600:web:e0b959c6bd387cc1f2c2f5',
    messagingSenderId: '409947639600',
    projectId: 'stellar-pos-8384a',
    authDomain: 'stellar-pos-8384a.firebaseapp.com',
    storageBucket: 'stellar-pos-8384a.firebasestorage.app',
    measurementId: 'G-S4MF4J53LR',
  );
}
