// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiaC9hQlIlJR8PMT43z02Bz3ZkL12C55A',
    appId: '1:837639639748:web:329f991ef2976a3692af91',
    messagingSenderId: '837639639748',
    projectId: 'stellar-pos-86f0c',
    authDomain: 'stellar-pos-86f0c.firebaseapp.com',
    storageBucket: 'stellar-pos-86f0c.firebasestorage.app',
    measurementId: 'G-ZPDMQXZQJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZGMyIavOtNNwSex2-6G1EXB4k62FkS4I',
    appId: '1:837639639748:android:12c192126ca3e5d192af91',
    messagingSenderId: '837639639748',
    projectId: 'stellar-pos-86f0c',
    storageBucket: 'stellar-pos-86f0c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr0ki3tcb3mPiqDJw8Py2mwJspu5KkrWU',
    appId: '1:837639639748:ios:c6159361e7e771db92af91',
    messagingSenderId: '837639639748',
    projectId: 'stellar-pos-86f0c',
    storageBucket: 'stellar-pos-86f0c.firebasestorage.app',
    iosBundleId: 'com.example.stellarPos',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr0ki3tcb3mPiqDJw8Py2mwJspu5KkrWU',
    appId: '1:837639639748:ios:be35eb5e30a9f56192af91',
    messagingSenderId: '837639639748',
    projectId: 'stellar-pos-86f0c',
    storageBucket: 'stellar-pos-86f0c.firebasestorage.app',
    iosBundleId: 'com.zeyteck.stellarpos',
  );
}
