import 'package:stellar_pos/core/data/storage/local_storage.dart';
import 'package:stellar_pos/core/utils/id_generator.dart';

/// Stores the stable device identity plus the cloud store identity selected
/// for this installation.
///
/// The internal store id is generated by Firestore when a store is created.
/// The store name and invitation code are display/configuration values linked
/// to that immutable store id.
class CloudIdentityStore {
  static const _boxName = 'cloud_sync_identity';
  static const _deviceIdKey = 'deviceId';
  static const _storeIdKey = 'storeId';
  static const _storeNameKey = 'storeName';
  static const _inviteCodeKey = 'inviteCode';

  Future<String> getOrCreateDeviceId() async {
    final box = await LocalStorage.openBox(_boxName);
    final existing = box.get(_deviceIdKey)?.toString().trim();
    if (existing != null && existing.isNotEmpty) return existing;

    final deviceId = IdGenerator.newId();
    await box.put(_deviceIdKey, deviceId);
    return deviceId;
  }

  Future<String?> getStoreId() async {
    final box = await LocalStorage.openBox(_boxName);
    final value = box.get(_storeIdKey)?.toString().trim();
    return value == null || value.isEmpty ? null : value;
  }

  Future<String?> getStoreName() async {
    final box = await LocalStorage.openBox(_boxName);
    final value = box.get(_storeNameKey)?.toString().trim();
    return value == null || value.isEmpty ? null : value;
  }

  Future<String?> getInviteCode() async {
    final box = await LocalStorage.openBox(_boxName);
    final value = box.get(_inviteCodeKey)?.toString().trim();
    return value == null || value.isEmpty ? null : value;
  }

  Future<void> setStoreIdentity({
    required String storeId,
    required String storeName,
    String? inviteCode,
  }) async {
    final normalizedId = storeId.trim();
    final normalizedName = storeName.trim();
    if (normalizedId.isEmpty) {
      throw ArgumentError.value(storeId, 'storeId', 'cannot be empty');
    }
    if (normalizedName.isEmpty) {
      throw ArgumentError.value(storeName, 'storeName', 'cannot be empty');
    }

    final box = await LocalStorage.openBox(_boxName);
    await box.put(_storeIdKey, normalizedId);
    await box.put(_storeNameKey, normalizedName);

    final normalizedInvite = inviteCode?.trim() ?? '';
    if (normalizedInvite.isEmpty) {
      await box.delete(_inviteCodeKey);
    } else {
      await box.put(_inviteCodeKey, normalizedInvite);
    }
  }

  Future<void> setStoreName(String storeName) async {
    final normalized = storeName.trim();
    if (normalized.isEmpty) {
      throw ArgumentError.value(storeName, 'storeName', 'cannot be empty');
    }

    final box = await LocalStorage.openBox(_boxName);
    await box.put(_storeNameKey, normalized);
  }

  Future<void> setInviteCode(String inviteCode) async {
    final normalized = inviteCode.trim();
    if (normalized.isEmpty) {
      throw ArgumentError.value(inviteCode, 'inviteCode', 'cannot be empty');
    }

    final box = await LocalStorage.openBox(_boxName);
    await box.put(_inviteCodeKey, normalized);
  }

  Future<void> clearStore() async {
    final box = await LocalStorage.openBox(_boxName);
    await box.delete(_storeIdKey);
    await box.delete(_storeNameKey);
    await box.delete(_inviteCodeKey);
  }
}
