import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import 'package:stellar_pos/core/constants/app_constants.dart';
import 'package:stellar_pos/core/models/product.dart';
import 'package:stellar_pos/core/models/purchase.dart';
import 'package:stellar_pos/core/providers/product_provider.dart';
import 'package:stellar_pos/core/providers/providers_provider.dart';
import 'package:stellar_pos/core/providers/purchases_provider.dart';
import 'package:stellar_pos/core/utils/id_generator.dart';

class PurchaseCreationDialog extends StatefulWidget {
  const PurchaseCreationDialog({super.key});
  static Future<bool?> show(BuildContext context) => showDialog<bool>(context: context, barrierDismissible: false, builder: (_) => const PurchaseCreationDialog());
  @override State<PurchaseCreationDialog> createState() => _PurchaseCreationDialogState();
}
class _PurchaseCreationDialogState extends State<PurchaseCreationDialog> {
  static const _timeout = Duration(milliseconds: 120);
  final _invoice = TextEditingController(); final _search = TextEditingController(); final _items = <_DraftPurchaseItem>[]; final _skip = <String>{};
  String _buffer = ''; DateTime? _lastKey; DateTime _date = DateTime.now(); String? _distributor; bool _saving = false;
  @override void initState() { super.initState(); FocusManager.instance.addEarlyKeyEventHandler(_barcodeKey); }
  @override void dispose() { FocusManager.instance.removeEarlyKeyEventHandler(_barcodeKey); _invoice.dispose(); _search.dispose(); super.dispose(); }
  String _money(double v) => '\$${v.toStringAsFixed(2)}';
  String _dateText(DateTime v) => '${v.day.toString().padLeft(2, '0')}/${v.month.toString().padLeft(2, '0')}/${v.year}';
  KeyEventResult _barcodeKey(KeyEvent e) { if (!mounted || ModalRoute.of(context)?.isCurrent != true || e is! KeyDownEvent) return KeyEventResult.ignored; if (FocusManager.instance.primaryFocus?.context?.findAncestorWidgetOfExactType<EditableText>() != null) return KeyEventResult.ignored; final enter = e.logicalKey == LogicalKeyboardKey.enter || e.logicalKey == LogicalKeyboardKey.numpadEnter; if (enter) { final code = _buffer; _buffer = ''; _lastKey = null; if (code.length >= 6) { final p = context.read<ProductProvider>().findByBarcode(code); if (p != null) { _search.clear(); FocusManager.instance.primaryFocus?.unfocus(); _addProduct(p); return KeyEventResult.handled; } } return KeyEventResult.ignored; } final c = e.character; if (c == null || c.isEmpty || c.trim().isEmpty) return KeyEventResult.ignored; final now = DateTime.now(); _buffer = _lastKey == null || now.difference(_lastKey!) > _timeout ? c : _buffer + c; _lastKey = now; return KeyEventResult.handled; }
  List<Product> _products(ProductProvider p) { final q = _search.text.trim().toLowerCase(); if (q.isEmpty) return p.products; return p.products.where((x) => x.name.toLowerCase().contains(q) || x.barcode.toLowerCase().contains(q) || x.brand.toLowerCase().contains(q)).toList(); }
  double get _total => _items.fold(0, (s, x) => s + x.totalCost); int get _received => _items.fold(0, (s, x) => s + x.received); int get _bonuses => _items.fold(0, (s, x) => s + x.bonusQuantity);
  @override Widget build(BuildContext context) { final ps = _products(context.watch<ProductProvider>()); final ds = context.watch<ProvidersProvider>().distributors; return Dialog(insetPadding: const EdgeInsets.all(18), child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 1180, maxHeight: 850), child: Column(children: [_header(), const Divider(height: 1), Padding(padding: const EdgeInsets.all(14), child: _info(ds)), Expanded(child: Padding(padding: const EdgeInsets.fromLTRB(14, 0, 14, 14), child: Row(children: [Expanded(flex: 5, child: _picker(ps)), const SizedBox(width: 14), Expanded(flex: 6, child: _list())]))), const Divider(height: 1), _footer()]))); }
  Widget _header() => Padding(padding: const EdgeInsets.fromLTRB(20, 14, 12, 12), child: Row(children: [const Icon(Icons.shopping_bag_outlined, color: AppColors.primary, size: 25), const SizedBox(width: 10), const Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Nueva compra', style: AppTextStyles.sectionTitle), SizedBox(height: 2), Text('Registra productos, bonificaciones y costos.', style: TextStyle(fontSize: 11, color: AppColors.textSecondary))])), IconButton(onPressed: _saving ? null : () => Navigator.pop(context, false), icon: const Icon(Icons.close))]));
  Widget _info(List<String> d) => Row(children: [Expanded(flex: 2, child: DropdownButtonFormField<String>(initialValue: _distributor, isExpanded: true, decoration: const InputDecoration(labelText: 'Distribuidora', prefixIcon: Icon(Icons.storefront_outlined), border: OutlineInputBorder(), isDense: true), items: d.map((x) => DropdownMenuItem(value: x, child: Text(x, overflow: TextOverflow.ellipsis))).toList(), onChanged: _saving ? null : (x) => setState(() => _distributor = x))), const SizedBox(width: 10), Expanded(child: TextField(controller: _invoice, enabled: !_saving, decoration: const InputDecoration(labelText: 'N.º de factura', prefixIcon: Icon(Icons.receipt_long_outlined), border: OutlineInputBorder(), isDense: true))), const SizedBox(width: 10), Expanded(child: InkWell(onTap: _saving ? null : _pickDate, child: InputDecorator(decoration: const InputDecoration(labelText: 'Fecha', prefixIcon: Icon(Icons.calendar_today_outlined), border: OutlineInputBorder(), isDense: true), child: Text(_dateText(_date))))), const SizedBox(width: 10), Container(padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 11), decoration: BoxDecoration(color: AppColors.inputBackground, borderRadius: BorderRadius.circular(9), border: Border.all(color: AppColors.border)), child: const Row(mainAxisSize: MainAxisSize.min, children: [Icon(Icons.payments_outlined, size: 18, color: AppColors.successGreen), SizedBox(width: 7), Text('Contado', style: TextStyle(fontSize: 12, fontWeight: FontWeight.w700))]))]);
  Widget _picker(List<Product> ps) => Container(decoration: BoxDecoration(color: AppColors.cardBackground, borderRadius: BorderRadius.circular(12), border: Border.all(color: AppColors.border)), child: Column(children: [Padding(padding: const EdgeInsets.fromLTRB(12, 12, 12, 8), child: Row(children: [const Expanded(child: Text('Agregar productos', style: TextStyle(fontSize: 13, fontWeight: FontWeight.w800))), Text('${ps.length} disponibles', style: const TextStyle(fontSize: 10, color: AppColors.textMuted))])), Padding(padding: const EdgeInsets.fromLTRB(12, 0, 12, 10), child: TextField(controller: _search, onChanged: (_) => setState(() {}), decoration: const InputDecoration(hintText: 'Buscar producto...', prefixIcon: Icon(Icons.search), border: OutlineInputBorder(), isDense: true))), const Divider(height: 1), Expanded(child: ps.isEmpty ? const Center(child: Text('No hay productos registrados.')) : GridView.builder(padding: const EdgeInsets.all(10), gridDelegate: const SliverGridDelegateWithMaxCrossAxisExtent(maxCrossAxisExtent: 175, mainAxisExtent: 132, crossAxisSpacing: 8, mainAxisSpacing: 8), itemCount: ps.length, itemBuilder: (_, i) => _productCard(ps[i]))) ]));
  Widget _productCard(Product p) { final b = _decode(p.imageData); return InkWell(onTap: _saving ? null : () => _addProduct(p), borderRadius: BorderRadius.circular(10), child: Container(padding: const EdgeInsets.all(8), decoration: BoxDecoration(color: AppColors.inputBackground, borderRadius: BorderRadius.circular(10), border: Border.all(color: AppColors.border)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Expanded(child: Center(child: b == null ? const Icon(Icons.inventory_2_outlined, size: 32, color: AppColors.textMuted) : Image.memory(b, fit: BoxFit.contain))), Text(p.name, maxLines: 2, overflow: TextOverflow.ellipsis, style: const TextStyle(fontSize: 10, fontWeight: FontWeight.w700)), const SizedBox(height: 2), Text('Costo ${_money(p.cost)}  •  Stock ${p.stock}', style: const TextStyle(fontSize: 8, color: AppColors.textSecondary))]))); }
  void _addProduct(Product p) { final i = _items.indexWhere((x) => x.product.id == p.id); setState(() { if (i >= 0) { final x = _items[i]; _items[i] = x.copyWith(purchasedQuantity: x.purchasedQuantity + 1); } else { _items.add(_DraftPurchaseItem(product: p, purchasedQuantity: 1, bonusQuantity: 0, unitCost: p.cost, salePrice: p.price, discount: 0)); } }); }
  Widget _list() => Container(decoration: BoxDecoration(color: AppColors.cardBackground, borderRadius: BorderRadius.circular(12), border: Border.all(color: AppColors.border)), child: Column(children: [Padding(padding: const EdgeInsets.all(12), child: Row(children: [const Expanded(child: Text('Productos de la compra', style: TextStyle(fontSize: 13, fontWeight: FontWeight.w800))), if (_items.isNotEmpty) Text('$_received recibidas  •  $_bonuses bonificadas', style: const TextStyle(fontSize: 10, color: AppColors.textSecondary))])), const Divider(height: 1), Expanded(child: _items.isEmpty ? const Center(child: Column(mainAxisSize: MainAxisSize.min, children: [Icon(Icons.add_shopping_cart_outlined, size: 44, color: AppColors.textMuted), SizedBox(height: 8), Text('Selecciona productos de la izquierda', style: TextStyle(fontSize: 12, color: AppColors.textSecondary)), SizedBox(height: 3), Text('El escáner está activo al abrir esta ventana.', style: TextStyle(fontSize: 10, color: AppColors.textMuted))])) : ListView.separated(padding: const EdgeInsets.all(10), itemCount: _items.length, separatorBuilder: (_, __) => const SizedBox(height: 8), itemBuilder: (_, i) => _item(i))) ]));
  Widget _item(int i) => _PurchaseItemCard(key: ValueKey(_items[i].product.id), item: _items[i], money: _money, onChanged: (x) => setState(() => _items[i] = x), onDelete: () => setState(() => _items.removeAt(i)));
  Widget _footer() => Padding(padding: const EdgeInsets.fromLTRB(20, 11, 20, 13), child: Row(children: [_stat('Unidades recibidas', '$_received'), const SizedBox(width: 14), _stat('Bonificaciones', '$_bonuses', color: AppColors.successGreen), const Spacer(), Column(crossAxisAlignment: CrossAxisAlignment.end, children: [const Text('TOTAL PAGADO', style: TextStyle(fontSize: 9, color: AppColors.textMuted, fontWeight: FontWeight.w700)), Text(_money(_total), style: const TextStyle(fontSize: 21, fontWeight: FontWeight.w900, color: AppColors.primary))]), const SizedBox(width: 16), FilledButton.icon(onPressed: _saving || _items.isEmpty ? null : _save, icon: _saving ? const SizedBox(width: 16, height: 16, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white)) : const Icon(Icons.check), label: Text(_saving ? 'Guardando...' : 'Guardar compra'))]));
  Widget _stat(String l, String v, {Color? color}) => Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(l, style: const TextStyle(fontSize: 8, color: AppColors.textMuted)), const SizedBox(height: 2), Text(v, style: TextStyle(fontSize: 12, fontWeight: FontWeight.w800, color: color))]);
  Future<void> _pickDate() async { final p = await showDatePicker(context: context, firstDate: DateTime(2020), lastDate: DateTime(2100), initialDate: _date); if (p != null && mounted) setState(() => _date = DateTime(p.year, p.month, p.day, _date.hour, _date.minute)); }
  Future<void> _save() async { if (_distributor == null || _distributor!.trim().isEmpty) return _error('Selecciona una distribuidora.'); if (_items.isEmpty) return _error('Agrega al menos un producto.'); setState(() => _saving = true); try { final pp = context.read<ProductProvider>(); final changes = <_CostChange>[]; for (final x in _items) { if (x.purchasedQuantity <= 0) continue; final current = pp.findById(x.product.id); if (current != null && (current.cost - x.unitCost).abs() > .0001 && !_skip.contains(x.product.id)) changes.add(_CostChange(current, x.unitCost)); } if (changes.isNotEmpty) { final decisions = await showDialog<Map<String, _CostDecision>>(context: context, barrierDismissible: false, builder: (_) => _CostChangesDialog(changes)); if (!mounted || decisions == null) { setState(() => _saving = false); return; } for (final c in changes) { final d = decisions[c.product.id]; if (d?.updateCost == true) pp.updateProduct(c.product.copyWith(cost: c.newCost)); if (d?.skipFuture == true) _skip.add(c.product.id); } } for (final x in _items) { final current = pp.findById(x.product.id); if (current == null) continue; pp.updateProduct(current.copyWith(stock: current.stock + x.received, price: x.purchasedQuantity > 0 ? x.salePrice : current.price)); } final purchase = PurchaseRecord(id: IdGenerator.newId(), invoiceNumber: _invoice.text.trim(), distributorName: _distributor!.trim(), arrivalAt: _date, paymentMethod: 'Contado', items: _items.map((x) => PurchaseItemRecord(productId: x.product.id, productName: x.product.name, unit: x.product.unit, barcode: x.product.barcode, imageData: x.product.imageData, unitCost: x.unitCost, quantity: x.purchasedQuantity, bonusQuantity: x.bonusQuantity, totalQuantity: x.received, salePrice: x.salePrice, discount: x.discount, total: x.totalCost, effectiveUnitCost: x.effectiveUnitCost)).toList(), subtotal: _total, discount: _items.fold(0, (s, x) => s + x.discount), total: _total); context.read<PurchasesProvider>().addPurchase(purchase); if (mounted) Navigator.pop(context, true); } catch (e) { if (!mounted) return; setState(() => _saving = false); _error('No se pudo guardar la compra: $e'); } }
  void _error(String s) => ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(s)));
  Uint8List? _decode(String v) { if (v.trim().isEmpty) return null; try { return base64Decode(v.contains(',') ? v.split(',').last : v); } catch (_) { return null; } }
}
class _DraftPurchaseItem { final Product product; final int purchasedQuantity; final int bonusQuantity; final double unitCost; final double salePrice; final double discount; const _DraftPurchaseItem({required this.product, required this.purchasedQuantity, required this.bonusQuantity, required this.unitCost, required this.salePrice, required this.discount}); int get received => purchasedQuantity + bonusQuantity; double get totalCost => (purchasedQuantity * unitCost - discount).clamp(0, double.infinity).toDouble(); double get effectiveUnitCost => received == 0 ? 0 : totalCost / received; _DraftPurchaseItem copyWith({int? purchasedQuantity, int? bonusQuantity, double? unitCost, double? salePrice, double? discount}) => _DraftPurchaseItem(product: product, purchasedQuantity: purchasedQuantity ?? this.purchasedQuantity, bonusQuantity: bonusQuantity ?? this.bonusQuantity, unitCost: unitCost ?? this.unitCost, salePrice: salePrice ?? this.salePrice, discount: discount ?? this.discount); }
class _PurchaseItemCard extends StatefulWidget { final _DraftPurchaseItem item; final String Function(double) money; final ValueChanged<_DraftPurchaseItem> onChanged; final VoidCallback onDelete; const _PurchaseItemCard({super.key, required this.item, required this.money, required this.onChanged, required this.onDelete}); @override State<_PurchaseItemCard> createState() => _PurchaseItemCardState(); }
class _PurchaseItemCardState extends State<_PurchaseItemCard> {
  late TextEditingController _purchased, _bonus, _cost, _discount, _sale;
  @override void initState() { super.initState(); _purchased = TextEditingController(text: '${widget.item.purchasedQuantity}'); _bonus = TextEditingController(text: '${widget.item.bonusQuantity}'); _cost = TextEditingController(text: _display(widget.item.unitCost)); _discount = TextEditingController(text: _display(widget.item.discount)); _sale = TextEditingController(text: _display(widget.item.salePrice)); }
  String _display(double v) => widget.item.purchasedQuantity == 0 && widget.item.bonusQuantity > 0 ? '' : v.toStringAsFixed(2);
  @override void didUpdateWidget(covariant _PurchaseItemCard oldWidget) { super.didUpdateWidget(oldWidget); final a = oldWidget.item, b = widget.item; if (a.purchasedQuantity != b.purchasedQuantity && int.tryParse(_purchased.text) != b.purchasedQuantity) _set(_purchased, '${b.purchasedQuantity}'); if (a.bonusQuantity != b.bonusQuantity && int.tryParse(_bonus.text) != b.bonusQuantity) _set(_bonus, '${b.bonusQuantity}'); if (a.unitCost != b.unitCost && _double(_cost) != b.unitCost) _set(_cost, _display(b.unitCost)); if (a.discount != b.discount && _double(_discount) != b.discount) _set(_discount, _display(b.discount)); if (a.salePrice != b.salePrice && _double(_sale) != b.salePrice) _set(_sale, _display(b.salePrice)); }
  void _set(TextEditingController c, String v) { c.value = TextEditingValue(text: v, selection: TextSelection.collapsed(offset: v.length)); }
  @override void dispose() { _purchased.dispose(); _bonus.dispose(); _cost.dispose(); _discount.dispose(); _sale.dispose(); super.dispose(); }
  int _int(TextEditingController c) => int.tryParse(c.text.trim()) ?? 0; double _double(TextEditingController c) => double.tryParse(c.text.trim().replaceAll(',', '.')) ?? 0;
  void _emit() => widget.onChanged(widget.item.copyWith(purchasedQuantity: _int(_purchased).clamp(0, 1 << 30).toInt(), bonusQuantity: _int(_bonus).clamp(0, 1 << 30).toInt(), unitCost: _double(_cost).clamp(0, double.infinity).toDouble(), discount: _double(_discount).clamp(0, double.infinity).toDouble(), salePrice: _double(_sale).clamp(0, double.infinity).toDouble()));
  void _step(TextEditingController c, int d) { c.text = (_int(c) + d).clamp(0, 1 << 30).toInt().toString(); c.selection = TextSelection.collapsed(offset: c.text.length); _emit(); setState(() {}); }
  @override Widget build(BuildContext context) { final x = widget.item; return Container(padding: const EdgeInsets.fromLTRB(11, 10, 9, 11), decoration: BoxDecoration(color: AppColors.inputBackground, borderRadius: BorderRadius.circular(12), border: Border.all(color: AppColors.border)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [_image(x.product.imageData), const SizedBox(width: 10), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(x.product.name, maxLines: 1, overflow: TextOverflow.ellipsis, style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w800)), const SizedBox(height: 5), _prices(x.product)])), IconButton(tooltip: 'Eliminar', onPressed: widget.onDelete, icon: const Icon(Icons.delete_outline, size: 20))]), const SizedBox(height: 9), Container(padding: const EdgeInsets.all(9), decoration: BoxDecoration(color: AppColors.cardBackground, borderRadius: BorderRadius.circular(10), border: Border.all(color: AppColors.border)), child: Column(children: [Row(children: [Expanded(child: _qty(_purchased, 'Compradas', Icons.shopping_cart_outlined)), const SizedBox(width: 7), Expanded(child: _qty(_bonus, 'Bonificadas', Icons.card_giftcard_outlined)), const SizedBox(width: 7), Expanded(child: _readonly('Recibidas', '${x.received}', Icons.inventory_2_outlined)), const SizedBox(width: 7), Expanded(child: _field(_cost, 'Costo unitario', Icons.attach_money)), const SizedBox(width: 7), Expanded(child: _field(_discount, 'Descuento', Icons.discount_outlined, suffix: '\$ / %')), const SizedBox(width: 7), Expanded(child: _readonly('Total', widget.money(x.totalCost), Icons.calculate_outlined, color: AppColors.primary))]), const SizedBox(height: 9), Container(padding: const EdgeInsets.fromLTRB(10, 8, 10, 8), decoration: BoxDecoration(color: AppColors.inputBackground, borderRadius: BorderRadius.circular(9)), child: Row(children: [const Icon(Icons.sell_outlined, size: 17, color: AppColors.primary), const SizedBox(width: 7), const Text('Cambiar precio de venta', style: TextStyle(fontSize: 10, fontWeight: FontWeight.w700)), const Spacer(), Text('Actual ${widget.money(x.product.price)}', style: const TextStyle(fontSize: 9, color: AppColors.textSecondary)), const SizedBox(width: 8), SizedBox(width: 125, child: _field(_sale, 'Nuevo precio', Icons.edit_outlined))]))]))])); }
  Widget _prices(Product p) => Container(padding: const EdgeInsets.symmetric(horizontal: 9, vertical: 5), decoration: BoxDecoration(color: AppColors.cardBackground, borderRadius: BorderRadius.circular(7), border: Border.all(color: AppColors.border)), child: Row(mainAxisSize: MainAxisSize.min, children: [Text('Costo ${widget.money(p.cost)}', style: const TextStyle(fontSize: 9, fontWeight: FontWeight.w700)), const SizedBox(width: 12), Text('Venta ${widget.money(p.price)}', style: const TextStyle(fontSize: 9, fontWeight: FontWeight.w700))]));
  Widget _image(String data) { final b = _decode(data); return Container(width: 48, height: 48, clipBehavior: Clip.antiAlias, decoration: BoxDecoration(color: AppColors.cardBackground, borderRadius: BorderRadius.circular(8), border: Border.all(color: AppColors.border)), child: b == null ? const Icon(Icons.image_outlined, size: 21, color: AppColors.textMuted) : Image.memory(b, fit: BoxFit.contain)); }
  Uint8List? _decode(String v) { if (v.trim().isEmpty) return null; try { return base64Decode(v.contains(',') ? v.split(',').last : v); } catch (_) { return null; } }
  Widget _field(TextEditingController c, String label, IconData icon, {String? suffix}) => TextField(controller: c, keyboardType: const TextInputType.numberWithOptions(decimal: true), decoration: InputDecoration(labelText: label, prefixIcon: Icon(icon, size: 17), suffixText: suffix, border: const OutlineInputBorder(), isDense: true, contentPadding: const EdgeInsets.symmetric(horizontal: 8, vertical: 10)), onChanged: (_) { _emit(); setState(() {}); });
  Widget _qty(TextEditingController c, String label, IconData icon) => TextField(controller: c, keyboardType: TextInputType.number, decoration: InputDecoration(labelText: label, prefixIcon: Icon(icon, size: 17), suffixIcon: Row(mainAxisSize: MainAxisSize.min, children: [IconButton(visualDensity: VisualDensity.compact, tooltip: 'Disminuir', onPressed: () => _step(c, -1), icon: const Icon(Icons.remove, size: 16)), IconButton(visualDensity: VisualDensity.compact, tooltip: 'Aumentar', onPressed: () => _step(c, 1), icon: const Icon(Icons.add, size: 16))]), border: const OutlineInputBorder(), isDense: true, contentPadding: const EdgeInsets.symmetric(horizontal: 8, vertical: 10)), onChanged: (_) { _emit(); setState(() {}); });
  Widget _readonly(String label, String value, IconData icon, {Color? color}) => InputDecorator(decoration: InputDecoration(labelText: label, prefixIcon: Icon(icon, size: 17), border: const OutlineInputBorder(), filled: true, fillColor: AppColors.inputBackground, isDense: true, contentPadding: const EdgeInsets.symmetric(horizontal: 8, vertical: 10)), child: Text(value, style: TextStyle(fontSize: 13, fontWeight: FontWeight.w800, color: color)));
}
class _CostChange { final Product product; final double newCost; const _CostChange(this.product, this.newCost); }
class _CostDecision { final bool updateCost; final bool skipFuture; const _CostDecision({required this.updateCost, required this.skipFuture}); }
class _CostChangesDialog extends StatefulWidget { final List<_CostChange> changes; const _CostChangesDialog(this.changes); @override State<_CostChangesDialog> createState() => _CostChangesDialogState(); }
class _CostChangesDialogState extends State<_CostChangesDialog> {
  final _done = <String>{}; final _skip = <String, bool>{}; final _decisions = <String, _CostDecision>{};
  void _resolve(_CostChange c, bool update) { final id = c.product.id; _done.add(id); _decisions[id] = _CostDecision(updateCost: update, skipFuture: _skip[id] ?? false); if (_done.length == widget.changes.length) { Navigator.pop(context, _decisions); return; } setState(() {}); }
  void _skipAll() { for (final c in widget.changes) { _done.add(c.product.id); _decisions[c.product.id] = _CostDecision(updateCost: false, skipFuture: _skip[c.product.id] ?? false); } Navigator.pop(context, _decisions); }
  @override Widget build(BuildContext context) => Dialog(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 760, maxHeight: 760), child: Column(children: [Padding(padding: const EdgeInsets.fromLTRB(22, 18, 14, 10), child: Row(children: [Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('Actualizar costos', style: AppTextStyles.sectionTitle), const SizedBox(height: 4), Text('Estos ${widget.changes.length} productos tienen un costo diferente al registrado.', style: const TextStyle(fontSize: 12, color: AppColors.textSecondary))])), IconButton(onPressed: () => Navigator.pop(context), icon: const Icon(Icons.close))])), const Divider(height: 1), Expanded(child: ListView.separated(padding: const EdgeInsets.all(16), itemCount: widget.changes.length, separatorBuilder: (_, __) => const SizedBox(height: 10), itemBuilder: (_, i) => _card(widget.changes[i]))), Padding(padding: const EdgeInsets.fromLTRB(18, 5, 18, 16), child: Align(alignment: Alignment.centerRight, child: TextButton(onPressed: _skipAll, child: const Text('Saltar todos'))))])));
  Widget _card(_CostChange c) { final done = _done.contains(c.product.id); final b = _decode(c.product.imageData); return Opacity(opacity: done ? .5 : 1, child: Container(padding: const EdgeInsets.all(13), decoration: BoxDecoration(color: AppColors.inputBackground, borderRadius: BorderRadius.circular(12), border: Border.all(color: AppColors.border)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Container(width: 48, height: 48, clipBehavior: Clip.antiAlias, decoration: BoxDecoration(color: AppColors.cardBackground, borderRadius: BorderRadius.circular(8), border: Border.all(color: AppColors.border)), child: b == null ? const Icon(Icons.image_outlined, color: AppColors.textMuted) : Image.memory(b, fit: BoxFit.contain)), const SizedBox(width: 10), Expanded(child: Text(c.product.name, maxLines: 2, overflow: TextOverflow.ellipsis, style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w800))), if (done) const Icon(Icons.check_circle_outline, color: AppColors.successGreen)]), const SizedBox(height: 9), Container(padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10), decoration: BoxDecoration(color: AppColors.cardBackground, borderRadius: BorderRadius.circular(9)), child: Row(children: [Expanded(child: _price('Actual', c.product.cost)), const Icon(Icons.arrow_forward_outlined, size: 20, color: AppColors.textMuted), Expanded(child: _price('Nuevo', c.newCost, color: AppColors.successGreen))])), const SizedBox(height: 8), Container(width: double.infinity, padding: const EdgeInsets.symmetric(horizontal: 11, vertical: 9), decoration: BoxDecoration(color: AppColors.primary.withAlpha(18), borderRadius: BorderRadius.circular(9), border: Border.all(color: AppColors.primary.withAlpha(70))), child: const Text('El nuevo costo reemplazará al anterior.', style: TextStyle(fontSize: 11, color: AppColors.primary, fontWeight: FontWeight.w600))), const SizedBox(height: 8), Row(children: [Expanded(child: OutlinedButton.icon(onPressed: done ? null : () => _resolve(c, true), icon: const Icon(Icons.check, size: 17), label: Text('Registrar ${c.newCost.toStringAsFixed(2)} como costo'))), const SizedBox(width: 8), SizedBox(width: 96, child: OutlinedButton.icon(onPressed: done ? null : () => _resolve(c, false), icon: const Icon(Icons.close, size: 17), label: const Text('Saltar')))]), CheckboxListTile(value: _skip[c.product.id] ?? false, onChanged: done ? null : (v) => setState(() => _skip[c.product.id] = v ?? false), dense: true, contentPadding: EdgeInsets.zero, title: const Text('No volver a preguntarme para este producto', style: TextStyle(fontSize: 10)), subtitle: const Text('Solo durante este registro de compra.', style: TextStyle(fontSize: 8))) ])))); }
  Widget _price(String l, double v, {Color? color}) => Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(l, style: const TextStyle(fontSize: 9, color: AppColors.textMuted)), const SizedBox(height: 2), Text('\$${v.toStringAsFixed(2)}', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w900, color: color))]);
  Uint8List? _decode(String v) { if (v.trim().isEmpty) return null; try { return base64Decode(v.contains(',') ? v.split(',').last : v); } catch (_) { return null; } }
}
